BiluthyrningAB/BiluthyrningAB/Controllers/CarsController.cs
using BiluthyrningAB.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BiluthyrningAB.Models;
using BiluthyrningAB.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using BiluthyrningAB.Services.Repositories;

namespace BiluthyrningAB.Controllers
{
    public class CarsController : Controller
    {
        //private readonly AppDbContext _context;

        //public CarsController(AppDbContext context)
        //{
        //    _context = context;
        //}
        private readonly ICarsRepository _carsRepository;

        public CarsController(IRentalsRepository rentalsRepository, ICarsRepository carsRepository, ICustomersRepository customersRepository)
        {
            _carsRepository = carsRepository;
        }

        //GET: vy för index
        public async Task<IActionResult> Index()
        {
            //return View(_context.Cars);
            return View(await(Task.Run(() => _carsRepository.GetAllCars())));

        }

        //GET: vy för create
        public IActionResult Create()
        {
            //return View();
            CarVm carTypeVm = new CarVm();

            carTypeVm.CarTypes = GetCarTypeToSelectList();

            return View(carTypeVm);
        }

        private List<SelectListItem> GetCarTypeToSelectList()
        {
            string[] carTypesArray = Enum.GetNames(typeof(CarType));

            List<SelectListItem> listOfCarTypes = new List<SelectListItem>();

            foreach (var car in carTypesArray)
            {
                var y = new SelectListItem() { Text = car, Value = car };
                listOfCarTypes.Add(y);
            }
            return listOfCarTypes;
        }

        //POST: Skapa ny bil
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Guid id, [Bind("CarId,NumberPlate,CarType,NumberOfDrivenKm")] Car car)
        {
            if (ModelState.IsValid)
            {
                _carsRepository.AddCar(car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        //GET: vy för att ändra bil
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
                return NotFound();

            var car = _carsRepository.GetCarById(id);
            if (car == null)
                return NotFound();

            CarVm carTypeVm = new CarVm();

            carTypeVm.CarTypes = GetCarTypeToSelectList();
            carTypeVm.Car = car;

            return View(carTypeVm);
        }


        //POST: Ändra bilinfo
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CarId,NumberPlate,CarType,NumberOfDrivenKm")] Car car)
        {
            if (id != car.CarId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _carsRepository.UpdateCar(car);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExist(car.CarId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            CarVm carTypeVm = new CarVm();

            carTypeVm.CarTypes = GetCarTypeToSelectList();
            carTypeVm.Car = car;
            return View(carTypeVm);
        }

        //GET: vy för att ta bort bil
        public async Task<IActionResult> Delete(Guid? id)
        {
            //return View();
            if (id == null)
                return NotFound();

            var car = _carsRepository.GetCarById(id);
            if (car == null)
                return NotFound();

            return View(car);
        }

        //POST: ta bort bil
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var car = _carsRepository.GetCarById(id);
            _carsRepository.RemoveCar(car);
            return RedirectToAction(nameof(Index));
        }

        // GET: vy för detaljer
        public IActionResult Details(Guid? id)
        {
            if (id == null)
                return NotFound();

            var car = _carsRepository.GetCarById(id);

            if (car == null)
                return NotFound();

            return View(car);
        }

        private bool CarExist(Guid id)
        {
            return _carsRepository.CarExists(id);
        }
    }
}

BiluthyrningAB/BiluthyrningAB/Controllers/RentalsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using BiluthyrningAB.Models;
using Microsoft.EntityFrameworkCore;
using BiluthyrningAB.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using BiluthyrningAB.Services.Repositories;


namespace BiluthyrningAB.Controllers
{
    public class RentalsController : Controller
    {
        private readonly IRentalsRepository _rentalsRepository;
        private readonly ICarsRepository _carsRepository;
        private readonly ICustomersRepository _customersRepository;


        public RentalsController(IRentalsRepository rentalsRepository, ICarsRepository carsRepository, ICustomersRepository customersRepository)
        {
            _rentalsRepository = rentalsRepository;
            _carsRepository = carsRepository;
            _customersRepository = customersRepository;
        }
        // GET: Index för rentals
        public async Task<IActionResult> Index()
        {
            return View(await (Task.Run(() => _rentalsRepository.GetAllRentals())));
        }

        //GET: vyn där man skapar en bokning
        public IActionResult Create()
        {
            CreateRentalVm rentalVm = new CreateRentalVm();

            rentalVm.Cars = FillCarsListSelectListItems();

            rentalVm.Customers = FillCustomersListSelectListItems();

            return View(rentalVm);

        }

        public async Task<IActionResult> AllNonFinishedRentals()
        {
            var myTask = Task.Run(() => _rentalsRepository.GetRentalsByStatus(true));
            return View(await myTask);
        }


        public async Task<IActionResult> AllFinishedRentals()
        {
            var myTask = Task.Run(() => _rentalsRepository.GetRentalsByStatus(false));
            return View(await myTask);
        }

        public async Task<IActionResult> AllRentalsOnCustomer(Guid? CustomerId, Guid? RentalId)
        {
            var myTask = Task.Run(() => _rentalsRepository.GetRentalsForCertainCustomer(CustomerId));
            
                return View(await myTask);
            
        }

        private List<SelectListItem> FillCustomersListSelectListItems()
        {
            var customers = _customersRepository.GetAllCustomers();

            List<SelectListItem> listOfCustomers = new List<SelectListItem>();

            foreach (var customer in customers)
            {
                string wholeName = $"{customer.FirstName} {customer.LastName}";
                var x = new SelectListItem() { Text = wholeName, Value = customer.CustomerId.ToString() };
                listOfCustomers.Add(x);
            }
            return listOfCustomers;
        }

        private List<SelectListItem> FillCarsListSelectListItems()
        {
            var cars = _carsRepository.GetAllCars();

            List<SelectListItem> listOfCars = new List<SelectListItem>();

            foreach (var car in cars)
            {
                var y = new SelectListItem() { Text = car.NumberPlate, Value = car.CarId.ToString(), Group = new SelectListGroup { Name = car.CarType.ToString() } };
                listOfCars.Add(y);
            }
            return listOfCars;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RentalId,StartDate,CustomerId,CarId")] Rental rental)
        {
            rental.Ongoing = true;
            rental.EndDate = rental.StartDate;

            rental.Car = _carsRepository.GetCarById(rental.CarId);

            //om bilen är obokad sätter vi den till bokad
            if (rental.Car.Booked == false)
            {
                rental.Car.Booked = true;
            }
            else
            {
                ViewBag.Message = "Bilen är upptagen vid den önskade tidpunkten, vänligen välj en annan bil.";
                CreateRentalVm error_rentalVm = new CreateRentalVm();
                error_rentalVm.Cars = FillCarsListSelectListItems();
                error_rentalVm.Customers = FillCustomersListSelectListItems();
                return View(error_rentalVm);
            }
            if (ModelState.IsValid)
            {
                //lägger till bokning i systemet.
                rental.RentalId = Guid.NewGuid();
                _rentalsRepository.AddRental(rental);

                //uppdaterar till bokad bil
                _carsRepository.UpdateCar(rental.Car);

                return RedirectToAction(nameof(Index));
            }

            var viewmodel = new CreateRentalVm();
            viewmodel.Rental = rental;
            return View(viewmodel);

        }

        //GET: Vy slutföra bokning
        public IActionResult FinishRental(Guid? id)
        {
            var rental = _rentalsRepository.GetRentalById(id);

            if (id == null)
                return NotFound();

            if (rental == null)
                return NotFound();

            return View(rental);
        }

        //POST: Slutföra bokning
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FinishRental(Guid id, [Bind("RentalId,NewNumberKmDriven,StartDate,EndDate,CarId,CustomerId")] Rental rental)
        {
            rental.Car = _carsRepository.GetCarById(rental.CarId);
            rental.Customer = _customersRepository.GetCustomerById(rental.CustomerId);

            if (id != rental.RentalId)
            {
                return NotFound();
            }
            if (rental.Price < 0)
            {
                ViewBag.Message = "Återlämningsdatum måste vara senare än uthämtningsdatum";
                return View(rental);
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //avslutar bokning
                    rental.Ongoing = false;
                    //sätter bilen till ledig igen
                    rental.Car.Booked = false;
                    //uppdaterar bilens körda km
                    rental.Car.NumberOfDrivenKm = rental.NewNumberKmDriven;

                    _carsRepository.UpdateCar(rental.Car);

                    _rentalsRepository.UpdateRental(rental);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentalExist(rental.RentalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));

            }
            return View(rental);
        }

        //GET: vy för att ändra bokning
        public IActionResult Edit(Guid? id)
        {

            if (id == null)
                return NotFound();

            var rental = _rentalsRepository.GetRentalById(id);
            if (rental == null)
                return NotFound();

            return View(rental);
        }

        //POST: Ändra bokning
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("RentalId,NumberOfKm,StartDate,EndDate,Car")] Rental rental)
        {
            if (id != rental.RentalId)
            {
                return NotFound();
            }
            if (rental.Price < 0)
            {
                ViewBag.Message = "Återlämningsdatum måste vara senare än uthämtningsdatum";
                return View(rental);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _rentalsRepository.UpdateRental(rental);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentalExist(rental.RentalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rental);
        }

        //GET: vy för att ta bort en uthyrning
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
                return NotFound();

            var rental = _rentalsRepository.GetRentalById(id);
            if (rental == null)
                return NotFound();

            return View(rental);
        }

        //POST: ta bort en uthyrning
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var rental = _rentalsRepository.GetRentalById(id);
            _rentalsRepository.RemoveRental(rental);
            return RedirectToAction(nameof(Index));
        }

        //GET: vy för uthyrning - details
        public IActionResult Details(Guid? id)
        {
            if (id == null)
                return NotFound();

            var rental = _rentalsRepository.GetRentalById(id);
            if (rental == null)
                return NotFound();

            return View(rental);
        }

        //Kollar på id ifall uthyrningen existerar
        private bool RentalExist(Guid id)
        {
            return _rentalsRepository.RentalExists(id);
        }
    }
}

BiluthyrningAB/BiluthyrningAB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BiluthyrningAB</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <link scriptsrc="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">

    <!-- Latest compiled JavaScript -->
    <link scriptsrc="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js">

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header pull-left">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Biluthyrning AB</a>
            </div>
            <div class="navbar-collapse collapse" style="height: 50px">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown"
                           asp-area="" asp-controller="Rentals" asp-action="Index">
                            Bokningar
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Rentals" asp-action="Index">Alla bokningar</a></li>
                            <li><a asp-area="" asp-controller="Rentals" asp-action="AllNonFinishedRentals">Pågående</a></li>
                            <li><a asp-area="" asp-controller="Rentals" asp-action="AllFinishedRentals">Avslutade</a></li>

                        </ul>
                    <li><a asp-area="" asp-controller="Cars" asp-action="Index">Bilar</a></li>
                    <li><a asp-area="" asp-controller="Customers" asp-action="Index">Kunder</a></li>

                </ul>
            </div>
        </div>
    </nav>


    <partial name="_CookieConsentPartial" />

    @RenderSection("Hero", required: false)

    <div class="container body-content">
        @RenderBody()
    </div>

    <footer>
        <div class="container-footer">
            <p>&copy; 2019 - Biluthyrning AB</p>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>